#
# Makefile for the Intel network device drivers.
#

obj-$(CONFIG_TEHUTI_C10GT) += tehuti-7.36.5.5.p1/
obj-$(CONFIG_TN4011_10GBASET) += tn40xx-0.3.6.14/
obj-$(CONFIG_TN4022_DXE810S) += tn4022-1.1.6.8_D/
